// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX8_d42l67idP6qI7yLUNgIfQw1g-8uW0',
    appId: '1:24866883211:web:e62d263556fb13de44368e',
    messagingSenderId: '24866883211',
    projectId: 'chat-application-66df6',
    authDomain: 'chat-application-66df6.firebaseapp.com',
    storageBucket: 'chat-application-66df6.firebasestorage.app',
    measurementId: 'G-YB0E7DGFJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdt6T_bJVeZSjgeKj_czF_D6L_RXBlitc',
    appId: '1:24866883211:android:af623109979d13ed44368e',
    messagingSenderId: '24866883211',
    projectId: 'chat-application-66df6',
    storageBucket: 'chat-application-66df6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnXSuTMppfee59iJviOdTHi8S295W0VGI',
    appId: '1:24866883211:ios:dfc9ea36effd460e44368e',
    messagingSenderId: '24866883211',
    projectId: 'chat-application-66df6',
    storageBucket: 'chat-application-66df6.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnXSuTMppfee59iJviOdTHi8S295W0VGI',
    appId: '1:24866883211:ios:dfc9ea36effd460e44368e',
    messagingSenderId: '24866883211',
    projectId: 'chat-application-66df6',
    storageBucket: 'chat-application-66df6.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX8_d42l67idP6qI7yLUNgIfQw1g-8uW0',
    appId: '1:24866883211:web:e37e4cfc3fe1a9a744368e',
    messagingSenderId: '24866883211',
    projectId: 'chat-application-66df6',
    authDomain: 'chat-application-66df6.firebaseapp.com',
    storageBucket: 'chat-application-66df6.firebasestorage.app',
    measurementId: 'G-PHMHQF9YE5',
  );
}
